### ISSUE TITLE
OpenBSD 6.8 compile problem (use gmake)

### ISSUE THREAD

**Issue by zak1207** [pcherenkov/udpxy#21]
udpxy-1.0-25.0 has error when compile on OpenBSD 6.8 uses **gmake**.

```
gmake[1]: Entering directory '/home/builder/udpxy-1.0-25.0/chipmunk'
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c util.c -o util.o
util.c:857:16: error: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to
      9223372036854775808 [-Werror,-Wimplicit-int-float-conversion]
    if( dval > LONG_MAX || dval < LONG_MIN )
             ~ ^~~~~~~~
/usr/include/sys/limits.h:63:19: note: expanded from macro 'LONG_MAX'
# define LONG_MAX       0x7fffffffffffffffL
                        ^~~~~~~~~~~~~~~~~~~
1 error generated.
gmake[1]: *** [Makefile:106: util.o] Error 1
gmake[1]: Leaving directory '/home/builder/udpxy-1.0-25.0/chipmunk'
gmake: *** [Makefile:110: release] Error 2
obsd68$
```

Version 1.0.24.1 compile successfully.

**Comment by pcherenkov** [comment]
Please try bug21-longmax branch, let me know if it builds well.

**Comment by zak1207** [comment]
`obsd68$ cd udpxy-bug21-longmax/chipmunk/
obsd68$ gmake
cc  -DUDPXREC_MOD -MM udpxy.c sloop.c rparse.c util.c prbuf.c ifaddr.c ctx.c mkpg.c rtp.c uopt.c dpkt.c netop.c extrn.c main.c udpxrec.c > udpxy.dep

Making a [release] version (use 'debug' target as an alternative)

gmake[1]: Entering directory '/home/builder/udpxy-bug21-longmax/chipmunk'
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c udpxy.c -o udpxy.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c sloop.c -o sloop.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c rparse.c -o rparse.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c util.c -o util.o
util.c:868:16: error: implicit conversion from 'long long' to 'double' changes value from
      9223372036854775807 to 9223372036854775808 [-Werror,-Wimplicit-int-float-conversion]
    if( dval > LLONG_MAX || dval < LLONG_MIN )
             ~ ^~~~~~~~~
/usr/include/sys/limits.h:76:20: note: expanded from macro 'LLONG_MAX'
# define LLONG_MAX      0x7fffffffffffffffLL
                        ^~~~~~~~~~~~~~~~~~~~
1 error generated.
gmake[1]: *** [Makefile:106: util.o] Error 1
gmake[1]: Leaving directory '/home/builder/udpxy-bug21-longmax/chipmunk'
gmake: *** [Makefile:110: release] Error 2
obsd68$
`

**Comment by zak1207** [comment]
Sorry, version 1.0.24.1 on OpenBSD 6.8 has compile error too.

**Comment by pcherenkov** [comment]
Please pull udpxy-bug21-longmax and re-try.

**Comment by zak1207** [comment]
```
obsd68$ cd udpxy-bug21-longmax/chipmunk/
obsd68$ gmake
cc  -DUDPXREC_MOD -MM udpxy.c sloop.c rparse.c util.c prbuf.c ifaddr.c ctx.c mkpg.c rtp.c uopt.c dpkt.c netop.c extrn.c main.c udpxrec.c > udpxy.dep

Making a [release] version (use 'debug' target as an alternative)

gmake[1]: Entering directory '/home/builder/udpxy-bug21-longmax/chipmunk'
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c udpxy.c -o udpxy.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c sloop.c -o sloop.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c rparse.c -o rparse.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c util.c -o util.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c prbuf.c -o prbuf.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c ifaddr.c -o ifaddr.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c ctx.c -o ctx.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c mkpg.c -o mkpg.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c rtp.c -o rtp.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c uopt.c -o uopt.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c dpkt.c -o dpkt.o
cc -W -Wall -Werror --pedantic   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c netop.c -o netop.o
netop.c:137:27: error: variable has incomplete type 'struct ip_mreq_source'
    struct ip_mreq_source group_source_req;
                          ^
netop.c:137:12: note: forward declaration of 'struct ip_mreq_source'
    struct ip_mreq_source group_source_req;
           ^
netop.c:159:59: error: use of undeclared identifier 'IP_ADD_SOURCE_MEMBERSHIP'
      mreq_operation = ( ( strcmp("ADD", opname) == 0 ) ? IP_ADD_SOURCE_MEMBERSHIP : IP_DROP_SOURCE_MEMBERSHIP );
                                                          ^
netop.c:159:86: error: use of undeclared identifier 'IP_DROP_SOURCE_MEMBERSHIP'
      mreq_operation = ( ( strcmp("ADD", opname) == 0 ) ? IP_ADD_SOURCE_MEMBERSHIP : IP_DROP_SOURCE_MEMBERSHIP );
                                                                                     ^
3 errors generated.
gmake[1]: *** [Makefile:106: netop.o] Error 1
gmake[1]: Leaving directory '/home/builder/udpxy-bug21-longmax/chipmunk'
gmake: *** [Makefile:110: release] Error 2
obsd68$

```

**Comment by pcherenkov** [comment]
This seems to be a separate issue with SSM support under OpenBSD 6.8. I don't have a VM for it now so I cannot check what exactly is the issue here. I'll leave it to the community for now to investigate and branch out a compliant version.

For you my recommendation is to take a version prior to the SSM support (.24) and patch it using the changes in the last commit (this will take care of the type-conversion warning).

**Comment by zak1207** [comment]
Your solution with the **udpxy-1.0-24.1** version with the patch **really helped**. **Thank you very much!**
